//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anda.Fluid.Domain.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class afmdbEntities : DbContext
    {
        public afmdbEntities()
            : base("name=afmdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<conveyor> conveyor { get; set; }
        public virtual DbSet<machine> machine { get; set; }
        public virtual DbSet<pattern> pattern { get; set; }
        public virtual DbSet<patternsetting> patternsetting { get; set; }
        public virtual DbSet<tbjtvalveprm> tbjtvalveprm { get; set; }
        public virtual DbSet<tbsvvalveprm> tbsvvalveprm { get; set; }
        public virtual DbSet<tbtimerecorder> tbtimerecorder { get; set; }
        public virtual DbSet<tbweightprm> tbweightprm { get; set; }
        public virtual DbSet<valve> valve { get; set; }
        public virtual DbSet<workpiece> workpiece { get; set; }
        public virtual DbSet<workpiecesetting> workpiecesetting { get; set; }
        public virtual DbSet<pattern_setting> pattern_setting { get; set; }
        public virtual DbSet<workpiece_pattern> workpiece_pattern { get; set; }
        public virtual DbSet<workpiece_setting> workpiece_setting { get; set; }
    }
}
