//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anda.Fluid.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbweightprm
    {
        public int WeightPrmId { get; set; }
        public Nullable<int> ShotDotsEachPattern { get; set; }
        public Nullable<int> PatternCount { get; set; }
        public Nullable<int> Interval { get; set; }
        public Nullable<double> CurrentWeight { get; set; }
        public Nullable<double> WeightBeforeSpray { get; set; }
        public Nullable<double> DifferWeight { get; set; }
        public Nullable<double> SingleDotWeight { get; set; }
        public Nullable<double> CumulativeWeight { get; set; }
        public Nullable<double> StandardWeight { get; set; }
        public Nullable<double> WeightOffset { get; set; }
        public Nullable<double> DiffOffsetPer { get; set; }
        public int valve_ValveId { get; set; }
    
        public virtual valve valve { get; set; }
    }
}
