//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anda.Fluid.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class valve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public valve()
        {
            this.tbjtvalveprm = new HashSet<tbjtvalveprm>();
            this.tbsvvalveprm = new HashSet<tbsvvalveprm>();
            this.tbweightprm = new HashSet<tbweightprm>();
        }
    
        public int ValveId { get; set; }
        public int MachineId { get; set; }
        public Nullable<int> ValveType { get; set; }
        public Nullable<int> ValveSeries { get; set; }
        public string Name { get; set; }
    
        public virtual machine machine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbjtvalveprm> tbjtvalveprm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbsvvalveprm> tbsvvalveprm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbweightprm> tbweightprm { get; set; }
    }
}
