//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anda.Fluid.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class workpiece_setting
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LotNum { get; set; }
        public string Operator { get; set; }
        public string Barcode { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<double> Mark1X { get; set; }
        public Nullable<double> Mark1Y { get; set; }
        public Nullable<double> Mark2X { get; set; }
        public Nullable<double> Mark2Y { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> VelXY { get; set; }
        public Nullable<double> VelZ { get; set; }
        public Nullable<double> AccXY { get; set; }
        public Nullable<double> AccZ { get; set; }
        public Nullable<double> SingleDotWt { get; set; }
        public Nullable<double> GluePressure1 { get; set; }
        public Nullable<double> GluePressure2 { get; set; }
        public Nullable<double> Temperature { get; set; }
    }
}
