//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anda.Fluid.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class workpiecesetting
    {
        public int Id { get; set; }
        public Nullable<double> VelXY { get; set; }
        public Nullable<double> VelZ { get; set; }
        public Nullable<double> AccXY { get; set; }
        public Nullable<double> AccZ { get; set; }
        public Nullable<double> SingleDotWt { get; set; }
        public Nullable<double> GluePressure1 { get; set; }
        public Nullable<double> GluePressure2 { get; set; }
        public Nullable<double> Temperature { get; set; }
        public int WorkpieceId { get; set; }
    
        public virtual workpiece workpiece { get; set; }
    }
}
