//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anda.Fluid.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class workpiece_pattern
    {
        public int WId { get; set; }
        public string WName { get; set; }
        public string WLotNum { get; set; }
        public string WOperator { get; set; }
        public string WBarcode { get; set; }
        public Nullable<System.DateTime> WStartTime { get; set; }
        public Nullable<System.DateTime> WEndTime { get; set; }
        public Nullable<int> WResult { get; set; }
        public Nullable<double> WMark1X { get; set; }
        public Nullable<double> WMark1Y { get; set; }
        public Nullable<double> WMark2X { get; set; }
        public Nullable<double> WMark2Y { get; set; }
        public Nullable<double> WHeight { get; set; }
        public int PId { get; set; }
        public string PName { get; set; }
        public string PLotNum { get; set; }
        public string POperator { get; set; }
        public string PBarcode { get; set; }
        public Nullable<System.DateTime> PStartTime { get; set; }
        public Nullable<System.DateTime> PEndTime { get; set; }
        public Nullable<int> PResult { get; set; }
        public Nullable<double> PMark1X { get; set; }
        public Nullable<double> PMark1Y { get; set; }
        public Nullable<double> PMark2X { get; set; }
        public Nullable<double> PMark2Y { get; set; }
        public Nullable<double> PHeight { get; set; }
        public int WorkpieceId { get; set; }
    }
}
